GET http://localhost:5000

###
GET http://localhost:5000/admin
Content-Type: application/json

{
  "userId": 3
}
###
GET http://localhost:5000/dashboard
Content-Type: application/json

{
  "userId": 1
}

###
GET http://localhost:5000/projects/2
Content-Type: application/json

{
  "userId": 1
}

###
GET http://localhost:5000/projects
Content-Type: application/json

{
  "userId": 1
}

###
DELETE  http://localhost:5000/projects/2
Content-Type: application/json

{
  "userId": 3
}